interview_types = ["coding", "ml_design", "ml_theory", "system_design", "math", "sql", "custom"]

# topic_lists = {
#     "coding": [
#         "Arrays",
#         "Strings",
#         "Linked Lists",
#         "Hash Tables",
#         "Dynamic Programming",
#         "Trees",
#         "Graphs",
#         "Sorting Algorithms",
#         "Binary Search",
#         "Recursion",
#         "Greedy Algorithms",
#         "Stack",
#         "Queue",
#         "Heaps",
#         "Depth-First Search (DFS)",
#         "Breadth-First Search (BFS)",
#         "Backtracking",
#         "Bit Manipulation",
#         "Binary Search Trees",
#         "Tries",
#     ],
#     "system_design": [
#         "Machine Learning Systems",
#         "Databases",
#         "Mobile Application Architecture",
#         "Web Services and APIs",
#         "Cloud Computing and Storage",
#         "Network Architecture and Protocols",
#         "Security and Compliance",
#         "Distributed Systems",
#         "Real-time and Batch Processing",
#         "Content Delivery Networks",
#     ],
#     "ml_design": [
#         "Computer Vision",
#         "Natural Language Processing",
#         "Recommendation Engines",
#         "Predictive Maintenance",
#         "Fraud Detection",
#         "Autonomous Driving",
#         "Retail Analytics",
#         "Speech Recognition",
#         "Customer Segmentation",
#         "Real-Time Bidding",
#         "Supply Chain Optimization",
#         "Video Analysis",
#         "Personalized Advertising",
#     ],
#     "math": [
#         "Probability Theory",
#         "Statistical Distributions",
#         "Hypothesis Testing",
#         "Linear Algebra",
#         "Calculus",
#         "Discrete Mathematics",
#         "Optimization Techniques",
#         "Bayesian Statistics",
#         "Regression Analysis",
#         "Combinatorics",
#         "Graph Theory",
#         "Game Theory",
#         "Numerical Methods",
#         "Logic Puzzles",
#         "Complexity Theory",
#         "Fourier Analysis",
#     ],
#     "sql": [
#         "Basic SQL Queries",
#         "Complex Joins",
#         "Subqueries",
#         "Aggregation and Grouping",
#         "Window Functions",
#         "Indexing and Performance Tuning",
#         "SQL Functions",
#         "Stored Procedures",
#         "Trigger and Events",
#         "Database Design",
#         "Normalization",
#         "Concurrency Control",
#         "Transaction Management",
#         "Backup and Recovery",
#         "Security in SQL",
#         "Data Import/Export",
#         "NoSQL vs SQL",
#         "Data Warehousing",
#         "SQL in Big Data Analytics",
#     ],
#     "ml_theory": [
#         "Supervised Learning",
#         "Unsupervised Learning",
#         "Reinforcement Learning",
#         "Deep Learning",
#         "Feature Engineering",
#         "Model Evaluation Metrics",
#         "Bias-Variance Tradeoff",
#         "Ensemble Methods",
#         "Neural Networks Architecture",
#         "Convolutional Neural Networks",
#         "Recurrent Neural Networks",
#         "Dimensionality Reduction",
#         "Large Language Models",
#         "Transformers",
#         "Diffusion Models",
#         "Clustering Algorithms",
#         "Gradient Descent",
#         "Regularization Techniques",
#         "Loss Functions",
#         "Optimization Algorithms",
#         "Generative Adversarial Networks",
#         "Transfer Learning",
#         "Explainable AI",
#     ],
#     "custom": [
#         "Specify any topic",
#     ],
# }

topic_lists = { 
    "coding": [
         "数组", 
         "字符串", 
         "链接列表", 
         "哈希表", 
         "动态规划", 
         "树", 
         "图形", 
         "排序算法", 
         "二分搜索", 
         "递归", 
         "贪婪算法", 
         "堆栈", 
         "队列", 
         "堆", 
         "深度优先搜索 (DFS)", 
         "广度优先搜索 (BFS)", 
         "回溯", 
         "位操作", 
         "二分搜索树", 
         "尝试",
    ], 
    "system_design": [ 
        "机器学习系统", 
        "数据库", 
        "移动应用程序架构", 
        "Web 服务和 API", 
        "云计算和存储", 
        "网络架构和协议", 
        "安全和合规", 
        "分布式系统", 
        "实时和批处理", 
        "内容交付网络", 
    ], 
    "ml_design": [ 
        "计算机视觉", 
        "自然语言处理", 
        "推荐引擎", 
        "预测性维护", 
        "欺诈检测", 
        "自动驾驶", 
        "零售分析", 
        "语音识别", 
        "客户细分", 
        "实时竞价", 
        "供应链优化", 
        "视频分析", 
        "个性化广告", 
    ], 
    "math": [ 
        "概率论", 
        "统计分布", 
        "假设检验", 
        "线性代数", 
        "微积分", 
        "离散数学", 
        "优化技术", 
        "贝叶斯统计", 
        "回归分析", 
        "组合学", 
        "图论", 
        "博弈论", 
        "数值方法", 
        "逻辑谜题", 
        "复杂性理论", 
        "傅里叶分析", 
    ], 
    "sql": [ 
        "基本 SQL 查询", 
        "复杂连接", 
        "子查询", 
        "聚合和分组", 
        "窗口函数", 
        "索引和性能调整", 
        "SQL 函数", 
        "存储过程", 
        "触发器和事件", 
        "数据库设计", 
        "规范化", 
        "并发控制", 
        "事务管理", 
        "备份和恢复", 
        "SQL 中的安全性", 
        "数据导入/导出", 
        "NoSQL 与 SQL", 
        "数据仓库", 
        "大数据分析中的 SQL", 
    ], 
    "ml_theory": [ 
        "监督学习", 
        "无监督学习", 
        "强化学习", 
        "深度学习", 
        "特征工程", 
        "模型评估指标", 
        "偏差-方差权衡", 
        "集成方法", 
        "神经网络架构", 
        "卷积神经网络", 
        "循环神经网络", 
        "维度减少", 
        "大型语言模型", 
        "Transformers", 
        "扩散模型", 
        "聚类算法", 
        "梯度下降", 
        "正则化技术", 
        "损失函数", 
        "优化算法", 
        "生成对抗网络", 
        "迁移学习", 
        "可解释的人工智能", 
    ], 
    "custom": [ 
        "指定任何主题", 
    ], 
}

# fixed_messages = {
#     "intro": "Nice to meet you! I'm your AI interviewer. Click 'Generate a problem' to start.",
#     "start": "Nice to meet you! I'm your AI interviewer. Read the problem statement. Using the record button to share your initial thoughts, or ask questions.",
#     "end": "The interview is complete. Thank you! Feedback will follow shortly.",
#     "error": "An error occurred. Please try again.",
# }

fixed_messages = {
    "intro": "很高兴认识你！我是你的 AI 面试官。点击‘生成问题’开始。",
    "start": "很高兴认识你！我是你的 AI 面试官。阅读问题陈述。使用录制按钮分享你的初步想法，或提出问题。",
    "end": "面试结束。谢谢！反馈将在稍后提供。",
    "error": "发生错误。请重试!",
}
